// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Email struct {
	ID             uint64         `db:"id" json:"id"`
	UserID         string         `db:"user_id" json:"user_id"`
	GmailMessageID string         `db:"gmail_message_id" json:"gmail_message_id"`
	SenderEmail    string         `db:"sender_email" json:"sender_email"`
	Subject        sql.NullString `db:"subject" json:"subject"`
	BodyPreview    sql.NullString `db:"body_preview" json:"body_preview"`
	ReceivedAt     time.Time      `db:"received_at" json:"received_at"`
	IsNotified     sql.NullBool   `db:"is_notified" json:"is_notified"`
	CreatedAt      sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID                  string         `db:"id" json:"id"`
	LineUserID          string         `db:"line_user_id" json:"line_user_id"`
	GmailAccessToken    sql.NullString `db:"gmail_access_token" json:"gmail_access_token"`
	GmailRefreshToken   sql.NullString `db:"gmail_refresh_token" json:"gmail_refresh_token"`
	GmailTokenExpiresAt sql.NullInt64  `db:"gmail_token_expires_at" json:"gmail_token_expires_at"`
	IsActive            sql.NullBool   `db:"is_active" json:"is_active"`
	CreatedAt           sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at" json:"updated_at"`
	GmailHistoryID      sql.NullInt64  `db:"gmail_history_id" json:"gmail_history_id"`
}
