// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type User struct {
	ID                  string         `db:"id" json:"id"`
	LineUserID          string         `db:"line_user_id" json:"line_user_id"`
	GmailAccessToken    sql.NullString `db:"gmail_access_token" json:"gmail_access_token"`
	GmailRefreshToken   sql.NullString `db:"gmail_refresh_token" json:"gmail_refresh_token"`
	GmailTokenExpiresAt sql.NullInt64  `db:"gmail_token_expires_at" json:"gmail_token_expires_at"`
	IsActive            sql.NullBool   `db:"is_active" json:"is_active"`
	CreatedAt           sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at" json:"updated_at"`
}
