// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEmail(ctx context.Context, arg CreateEmailParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteEmailsByUserID(ctx context.Context, userID string) error
	GetAllActiveUsers(ctx context.Context) ([]User, error)
	GetEmailByGmailMessageID(ctx context.Context, gmailMessageID string) (Email, error)
	GetEmailsByUserID(ctx context.Context, userID string) ([]Email, error)
	GetRecentEmails(ctx context.Context, arg GetRecentEmailsParams) ([]Email, error)
	GetUnnotifiedEmailsByUserID(ctx context.Context, userID string) ([]Email, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByLineUserID(ctx context.Context, lineUserID string) (User, error)
	MarkEmailAsNotified(ctx context.Context, gmailMessageID string) error
	UpdateEmailNotified(ctx context.Context, arg UpdateEmailNotifiedParams) error
	UpdateUserGmailTokens(ctx context.Context, arg UpdateUserGmailTokensParams) error
}

var _ Querier = (*Queries)(nil)
