// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    id,
    line_user_id,
    gmail_access_token,
    gmail_refresh_token,
    gmail_token_expires_at,
    is_active
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	ID                  string         `db:"id" json:"id"`
	LineUserID          string         `db:"line_user_id" json:"line_user_id"`
	GmailAccessToken    sql.NullString `db:"gmail_access_token" json:"gmail_access_token"`
	GmailRefreshToken   sql.NullString `db:"gmail_refresh_token" json:"gmail_refresh_token"`
	GmailTokenExpiresAt sql.NullInt64  `db:"gmail_token_expires_at" json:"gmail_token_expires_at"`
	IsActive            sql.NullBool   `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.exec(ctx, q.createUserStmt, createUser,
		arg.ID,
		arg.LineUserID,
		arg.GmailAccessToken,
		arg.GmailRefreshToken,
		arg.GmailTokenExpiresAt,
		arg.IsActive,
	)
}
